SELECT TOP (1000) [LogID],
    [CorrelationId],
    [AppName],
    [MuleNiverseRefnum],
    [MuleNiverse],
    [AuditLogTimeStamp],
    [FlowName],
    [Environment],
    [Layer],
    [LogType],
    [TracePoint],
    [Method],
    [Ipaddress],
    [AppEndPoint],
    [Params],
    [ClientId],
    [ClientName],
    [StatusCode],
    [ResponseTime],
    [ActivePayload],
    [InsertedDate],
    [ElementDescription],
    [Masking],
    [Crypto],
    [Logging],
    [Auditing],
    [MuleAppId],
    [LoopId],
    [LoopName],
    [ErrorLocation]
FROM [dbo].[AuditLog]
ORDER BY 1 DESC